### ISSUE TITLE
[feature proposal] JSX "Object Literal Property Value Shorthand"

### ISSUE THREAD

**Issue by tsnieman** [facebook/jsx#52] opened 2016-02-13 01:33 UTC
Common problem...
```jsx
<SomeComponent propVariable={propVariable} />
```
I repeat "propVariable". I find myself doing this a lot... like, several times for one JSX object (usually a React component) is not uncommon.

Proposed solution...
```jsx
<SomeComponent [propVariable] />
```
which would result to the same as the "common problem" example.

EDIT: [Dan Abramov suggested](https://twitter.com/dan_abramov/status/698321882920198144) this syntax instead:
```jsx
<SomeComponent {propVariable} />
```
because "Using square brackets as in computed property name is confusing. In ES6 whatever’s inside brackets *is* a string name variable" and "[...] would have been more consistent [...]".

Inspired by:
- Shorthand property names https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015
- Computed property names: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names
- CSS attribute selector: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

**Comment by jkoudys** [comment] 2016-02-13 02:32
Easy enough to do already in ES6 already with a spread + implicit prop names. I don't think we need more syntax muddying the waters when this is already solved.

```jsx
<SomeComponent {...{propVariable}} />
```
for the above, or multiple like so:
```jsx
<AnotherComponent {...{foo, bar, baz}} />
```

**Comment by sebmarkbage** [comment] 2016-02-16 19:33
Duplicate of: https://github.com/facebook/jsx/issues/23

Also, see relevant discussion in: https://github.com/facebook/jsx/issues/37

**Closed by sebmarkbage** 2016-02-16 19:33 UTC
